[build]
  # This will be run the site build
  command = "nvm ls-remote && yarn build"
  # This is the directory is publishing to netlify's CDN
  publish = "/"
  # functions build directory
  functions = "core/scripts"